export const theme = {
  colors: {
    bg: "#FBEFEF",
    card: "#FFFBF9",
    primary: "#A98FC2",
    primaryDark: "#8F6FA8",
    primarySoft: "#EFE8F5",
    text: "#4B3B47",
    textSoft: "#8B7488",
    border: "#F7DCE0",
    danger: "#C0574B",
    success: "#3C8C55",
    disabled: "#C2A9B4",
  },
  radius: { sm: 10, md: 16, lg: 22, pill: 999 },
  shadow: "0 12px 28px -14px rgba(169, 143, 194, 0.35)",
  font: "'Noto Sans KR', 'Pretendard', system-ui, -apple-system, 'Segoe UI', Roboto, 'Malgun Gothic', sans-serif",
};

const base = {
  fontFamily: theme.font,
  color: theme.colors.text,
};

export const s = {
  page: {
    ...base,
    maxWidth: 720,
    margin: "0 auto",
    padding: "0 20px 60px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "28px 0 8px",
  },
  logoDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: theme.colors.primary,
    display: "inline-block",
  },
  logoText: {
    fontSize: 20,
    fontWeight: 800,
    letterSpacing: -0.3,
  },
  logoImg: {
    height: 28,
    display: "block",
  },
  stepBar: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    padding: "8px 0 24px",
  },
  stepPill: (active) => ({
    padding: "8px 16px",
    borderRadius: theme.radius.pill,
    fontSize: 13,
    fontWeight: 600,
    background: active ? theme.colors.primary : "#fff",
    color: active ? "#fff" : theme.colors.textSoft,
    border: active ? "none" : `1px solid ${theme.colors.border}`,
    whiteSpace: "nowrap",
  }),
  card: {
    background: theme.colors.card,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.lg,
    padding: 28,
    boxShadow: theme.shadow,
  },
  title: {
    fontSize: 22,
    fontWeight: 800,
    margin: "0 0 6px",
    letterSpacing: -0.3,
  },
  subtitle: {
    color: theme.colors.textSoft,
    fontSize: 14,
    margin: "0 0 20px",
    lineHeight: 1.6,
  },
  tag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: theme.colors.primarySoft,
    color: theme.colors.primaryDark,
    borderRadius: theme.radius.pill,
    padding: "6px 14px",
    fontSize: 13,
    fontWeight: 700,
  },
  btnPrimary: (disabled) => ({
    ...base,
    background: disabled ? theme.colors.disabled : theme.colors.primary,
    color: "#fff",
    border: "none",
    borderRadius: theme.radius.pill,
    padding: "13px 26px",
    fontSize: 15,
    fontWeight: 700,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  btnSecondary: {
    ...base,
    background: "#fff",
    color: theme.colors.text,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.pill,
    padding: "13px 26px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },
  btnRow: {
    display: "flex",
    gap: 10,
    marginTop: 28,
  },
  input: {
    ...base,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.sm,
    padding: "9px 12px",
    fontSize: 14,
    background: "#fff",
  },
  errorText: {
    color: theme.colors.danger,
    fontSize: 13,
    fontWeight: 600,
    margin: "8px 0 0",
  },
  warningBox: {
    background: "#FFF6E5",
    border: "1px solid #FFE1A8",
    borderRadius: theme.radius.md,
    padding: 14,
    marginBottom: 18,
  },
  warningText: { margin: 0, color: "#8A6100", fontSize: 13, fontWeight: 600 },
  listBox: {
    maxHeight: 420,
    overflowY: "auto",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.md,
    padding: 6,
    marginBottom: 18,
    background: "#fff",
  },
  listRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 10px",
    borderBottom: `1px solid ${theme.colors.border}`,
  },
};
